import os

ticker_keywords = {
    "AAPL": ["AAPL", "Apple", "iPhone", "MacBook", "iPad"],
    "MSFT": ["MSFT", "Microsoft", "Windows", "Azure", "Xbox"],
    "GOOGL": ["GOOGL", "Alphabet", "Google", "YouTube", "Search"],
    "AMZN": ["AMZN", "Amazon", "AWS", "Prime", "Kindle"],
    "TSLA": ["TSLA", "Tesla", "Elon Musk", "EV", "Cybertruck"],
    "NVDA": ["NVDA", "NVIDIA", "GPU", "AI", "RTX"],
    "META": ["META", "Facebook", "Instagram", "WhatsApp", "Metaverse"],
    "BRK.B": ["BRK.B", "Berkshire Hathaway", "Warren Buffett", "Insurance", "Investments"],
    "JPM": ["JPM", "JP Morgan", "Banking", "Wealth", "Investment"],
    "V": ["Visa", "Credit Cards", "Payments", "Finance"],
    "JNJ": ["JNJ", "Johnson & Johnson", "Pharmaceuticals", "Vaccines", "Medical"],
    "XOM": ["XOM", "ExxonMobil", "Oil", "Gas", "Energy"],
    "PG": ["PG", "Procter & Gamble", "Consumer Goods", "Household", "Beauty"],
    "UNH": ["UNH", "UnitedHealth", "Healthcare", "Insurance", "Medicare"],
    "HD": ["HD", "Home Depot", "Retail", "Construction", "DIY"],
    "DIS": ["DIS", "Disney", "Disney+", "Marvel", "Theme Parks"],
    "PYPL": ["PYPL", "PayPal", "Venmo", "Payments", "Fintech"],
    "NFLX": ["NFLX", "Netflix", "Streaming", "Movies", "Series"],
    "KO": ["KO", "Coca-Cola", "Beverages", "Soda", "Soft Drinks"],
    "PEP": ["PEP", "Pepsi", "Snacks", "Frito-Lay", "Mountain Dew"],
    "ABNB": ["ABNB", "Airbnb", "Vacation Rental", "Travel", "Short-term Stay"],
    "NKE": ["NKE", "Nike", "Sneakers", "Sportswear", "Jordan"],
    "MCD": ["MCD", "McDonald's", "Fast Food", "Big Mac", "Restaurant"],
    "WMT": ["WMT", "Walmart", "Retail", "Groceries", "Sam's Club"],
    "GM": ["GM", "General Motors", "Chevrolet", "Cadillac", "EV"],
    "F": ["Ford", "Mustang", "F-150", "EV"],
    "INTC": ["INTC", "Intel", "Processors", "Chips", "Semiconductors"],
    "AMD": ["AMD", "Advanced Micro Devices", "Ryzen", "Radeon", "Gaming"],
    "BA": ["BA", "Boeing", "Airplanes", "Aerospace", "737"],
    "CAT": ["CAT", "Caterpillar", "Construction", "Heavy Equipment", "Mining"],
    "CVX": ["CVX", "Chevron", "Oil", "Gas", "Energy"],
    "MRK": ["MRK", "Merck", "Pharmaceuticals", "Medicine", "Vaccines"],
    "PFE": ["PFE", "Pfizer", "Vaccines", "Biotech", "COVID-19"],
    "T": ["AT&T", "Telecom", "Wireless", "5G"],
    "VZ": ["VZ", "Verizon", "Wireless", "5G", "Broadband"],
    "CSCO": ["CSCO", "Cisco", "Networking", "Cloud", "Cybersecurity"],
    "ADBE": ["ADBE", "Adobe", "Photoshop", "Illustrator", "Creative Cloud"],
    "CRM": ["CRM", "Salesforce", "CRM Software", "Cloud", "Enterprise"],
    "ORCL": ["ORCL", "Oracle", "Database", "Cloud", "Software"],
    "UBER": ["UBER", "Uber", "Rideshare", "Lyft", "Food Delivery"],
    "LYFT": ["LYFT", "Lyft", "Rideshare", "Transportation", "Uber"],
    "SQ": ["SQ", "Block", "Square", "Cash App", "Fintech"],
    "SHOP": ["SHOP", "Shopify", "E-commerce", "Online Stores", "DTC"],
    "ROKU": ["ROKU", "Streaming", "Smart TV", "Roku Channel", "Media"],
    "PLTR": ["PLTR", "Palantir", "Big Data", "AI", "Defense"],
    "SNAP": ["SNAP", "Snapchat", "Social Media", "AR", "Lenses"],
    "TWTR": ["TWTR", "Twitter", "Elon Musk", "X", "Tweets"],
    "DAL": ["DAL", "Delta Airlines", "Flights", "Air Travel", "Airline"],
    "AAL": ["AAL", "American Airlines", "Flights", "Travel", "Aviation"],
    "UAL": ["UAL", "United Airlines", "Flights", "Air Travel", "MileagePlus"],
    "LUV": ["LUV", "Southwest Airlines", "Flights", "Air Travel", "Bags Fly Free"],
    "TSCO": ["TSCO", "Tractor Supply", "Farming", "Rural", "DIY"],
    "TGT": ["TGT", "Target", "Retail", "Shopping", "Superstore"],
    "COST": ["COST", "Costco", "Warehouse Club", "Wholesale", "Bulk Shopping"],
    "LOW": ["LOW", "Lowe's", "Home Improvement", "DIY", "Tools"],
    "FDX": ["FDX", "FedEx", "Shipping", "Logistics", "Delivery"],
    "UPS": ["UPS", "United Parcel Service", "Shipping", "Logistics", "Delivery"],
    "BK": ["BK", "Bank of New York Mellon", "Investments", "Finance", "Wealth"],
    "GS": ["GS", "Goldman Sachs", "Investment Banking", "Wall Street", "Finance"],
    "C": ["Citigroup", "Banking", "Finance", "Credit Cards"],
    "USB": ["USB", "U.S. Bancorp", "Banking", "Wealth", "Loans"],
    "WFC": ["WFC", "Wells Fargo", "Banking", "Mortgage", "Finance"],
    "AXP": ["AXP", "American Express", "Credit Cards", "Rewards", "Banking"],
    "DFS": ["DFS", "Discover Financial", "Credit Cards", "Banking", "Loans"],
    "COIN": ["COIN", "Coinbase", "Crypto", "Bitcoin", "Ethereum"],
    "HOOD": ["HOOD", "Robinhood", "Trading", "Stocks", "Investing"],
    "SCHW": ["SCHW", "Charles Schwab", "Investments", "Trading", "Brokerage"],
    "BLK": ["BLK", "BlackRock", "Investments", "Wealth", "Asset Management"],
    "ARKK": ["ARKK", "ARK Invest", "Cathie Wood", "Innovation", "ETFs"],
    "SPY": ["SPY", "S&P 500 ETF", "Index Fund", "Investing", "Stock Market"],
    "QQQ": ["QQQ", "Nasdaq 100 ETF", "Tech Stocks", "Investing", "Index Fund"],
    "DIA": ["DIA", "Dow Jones ETF", "Investing", "Stock Market", "Index Fund"]
}
subreddits = [
    "stocks",
    "investing",
    "wallstreetbets",
    "options",
    "StockMarket",
    "securityanalysis",
    "finance",
    "economy",
    "Trading"
]

EMAIL_LIST = os.getenv("EMAIL_LIST", "").split(",")
