name: Deploy Docker container to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker container
        uses: azure/webapps-deploy@v2
        with:
          app-name: reddit-sentiment-bot
          images: reddit-sentiment-bot
